services:
  postgres:
    image: postgres:alpine
    container_name: event-ticketing-db
    environment:
      POSTGRES_DB: event_ticketing
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - event-ticketing-pgdata:/var/lib/postgresql/data

volumes:
  event-ticketing-pgdata: